# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/repos/arty-videocap/vivado/arty-videocap.cache/wt [current_project]
set_property parent.project_path C:/Users/user/repos/arty-videocap/vivado/arty-videocap.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/user/repos/arty-videocap/vivado/arty-videocap.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/user/repos/arty-videocap/hdl/ASYNC_FIFO.v
  C:/Users/user/repos/arty-videocap/hdl/BITSTREAM.v
  C:/Users/user/repos/arty-videocap/hdl/BRIDGE_ENC2ETH.v
  C:/Users/user/repos/arty-videocap/hdl/COMPONENT_ENCODER.v
  C:/Users/user/repos/arty-videocap/hdl/DECODER.v
  C:/Users/user/repos/arty-videocap/hdl/DSP.v
  C:/Users/user/repos/arty-videocap/hdl/INSERT_STUFF.v
  C:/Users/user/repos/arty-videocap/hdl/MJPG_ENCODER.v
  C:/Users/user/repos/arty-videocap/hdl/PASS_THROUGH.v
  C:/Users/user/repos/arty-videocap/hdl/RGB2YCBCR.v
  C:/Users/user/repos/arty-videocap/hdl/SASRESET.v
  C:/Users/user/repos/arty-videocap/hdl/SERIALIZER10.v
  C:/Users/user/repos/arty-videocap/hdl/VEC.v
  C:/Users/user/repos/arty-videocap/hdl/CAPTURE.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/DVI_Constants.vhd
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/SyncAsync.vhd
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/InputSERDES.vhd
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/PhaseAlign.vhd
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/SyncBase.vhd
  C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/TMDS_Receiver.vhd
  C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/hdl/add_crc32.vhd
  C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/hdl/add_preamble.vhd
  C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/hdl/ethernet_test.vhd
  C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/hdl/nibble_data.vhd
}
read_ip -quiet C:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]

read_ip -quiet C:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/user/repos/arty-videocap/vivado/arty-videocap.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/repos/arty-videocap/hdl/constrs.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/constrs.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/constrs_port.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/constrs_port.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/constrs_prop.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/constrs_prop.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty_ooc.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty_ooc.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb_ooc.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb_ooc.xdc]

read_xdc C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/ila_timing_workaround.xdc
set_property used_in_implementation false [get_files C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/ila_timing_workaround.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CAPTURE -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CAPTURE.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CAPTURE_utilization_synth.rpt -pb CAPTURE_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
