# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user/repos/arty-videocap/hdl/constrs.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/constrs_port.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/constrs_prop.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/ArtyEtherentTX/constraints/arty_ooc.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/dvi2rgb_ooc.xdc

# XDC: C:/Users/user/repos/arty-videocap/hdl/vivado-library/ip/dvi2rgb/src/ila_timing_workaround.xdc

# IP: ip/clk_wiz_2/clk_wiz_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] -quiet
